import Head from "next/head";
import Image from "next/image";
import { Inter } from "@next/font/google";
import styles from "../styles/Home.module.css";
import Logo from "../public/Logo.svg";
import MobileHome from "../component/mobile/Home/mobileHome";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  const openNav = () => {
    // alert("called")
    console.log("called")
  }
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <MobileHome/>
      
    </>
  );
}
